
-----------------------------------------------------
-- People often copy jobs. When they do, the GM table does not exist anymore.
-- This line makes the job code work both inside and outside of gamemode files.
-- You should not copy this line into your code.
local GAMEMODE = GAMEMODE or GM
--[[--------------------------------------------------------
Default teams. Please do not edit this file. Please use the darkrpmod addon instead.
--------------------------------------------------------]]
TEAM_SHKOLNIK = DarkRP.createJob("Школьник", {
    color = Color(20, 150, 20, 255),
    model = {
        "models/player/bully/bryce/bryce.mdl",
        "models/player/bully/chad/chad.mdl",
        "models/player/bully/constantinos/constantinos.mdl",
        "models/player/bully/damon/damon.mdl",
        "models/player/bully/derby/derby.mdl",
        "models/player/bully/gordon/gordon.mdl",
        "models/player/bully/ivan/ivan.mdl",
        "models/player/bully/parker/parker.mdl",
        "models/player/bully/tad/tad.mdl",
    },
    description = [[Самый обычный учащийся в средней школе номер 666.]],
    weapons = {},
    command = "shkolnik",
    max = 0,
    salary = GAMEMODE.Config.normalsalary,
    admin = 0,
    vote = false,
    hasLicense = false,
    candemote = false,
    category = "Школьники",
    pupil = true,
})

TEAM_HULIGAN = DarkRP.createJob("Хулиган", {
    color = Color(63, 63, 63, 255),
    model = {
        "models/player/bully/hal/hal.mdl",
        "models/player/bully/johnny/johnny.mdl",
        "models/player/bully/norton/norton.mdl",
        "models/player/bully/peanut/peanut.mdl",
        "models/player/bully/davis/davis.mdl",
        "models/player/bully/tom/tom.mdl",
        "models/player/bully/trent/trent.mdl",
    },
    description = [[Задира и грубиян. Делает все то, что не нравится другим. Обычно держатся группами.]],
    weapons = {},
    command = "huligan",
    max = 6,
    salary = GAMEMODE.Config.normalsalary,
    admin = 0,
    vote = false,
    hasLicense = false,
    category = "Школьники",
    pupil = true,
})

TEAM_HULIGANKA = DarkRP.createJob("Хулиганка", {
    color = Color(63, 63, 63, 255),
    model = {
        "models/mark2580/resident2/moira_prisoner_player.mdl",
    },
    description = [[Кто сказал, что девочки не умеют быть плохими?]],
    weapons = {},
    command = "huliganka",
    max = 6,
    salary = GAMEMODE.Config.normalsalary,
    admin = 0,
    vote = false,
    hasLicense = false,
    category = "Школьники",
    pupil = true,
})

TEAM_KACHOK = DarkRP.createJob("Качок", {
    color = Color(232, 143, 10, 255),
    model = {
        "models/player/bully/casey/casey.mdl",
        "models/player/bully/gord/gord.mdl",
        "models/player/bully/juri/juri.mdl",
        "models/player/bully/bif/bif.mdl",
    },
    description = [[Местный красавчик, звезда всей школы. Цепляй одноклассниц и заставляй ботанов делать за тебя домашку.]],
    weapons = { "weapon_dumbbell" },
    command = "kachok",
    max = 3,
    salary = GAMEMODE.Config.normalsalary,
    admin = 0,
    vote = false,
    hasLicense = false,
    category = "Школьники",
    pupil = true,
})

TEAM_OTLICHNIK = DarkRP.createJob("Ботан", {
    color = Color(35, 133, 32, 255),
    model = {
        "models/player/bully/algernon/algernon.mdl",
        "models/player/bully/bucky/bucky.mdl",
        "models/player/bully/cornelius/cornelius.mdl",
        "models/player/bully/earnest/earnest.mdl",
        "models/player/bully/trevor/trevor.mdl",
    },
    description = [[Зубрила, который знает ответ на любой вопрос учительницы. Помогает другим ученикам сделать домашку за деньги, и не только.]],
    weapons = {'keypad_cracker'},
    command = "botan",
    max = 0,
    salary = GAMEMODE.Config.normalsalary,
    admin = 0,
    vote = false,
    hasLicense = false,
    category = "Школьники",
    pupil = true,
})

TEAM_BARIGA = DarkRP.createJob("Барыга", {
    color = Color(173, 173, 173, 255),
    model = {
        "models/gonzo/simoncostumes/simon/simon.mdl",
        "models/gonzo/simoncostumes/simonaom/simonaom.mdl",
        "models/gonzo/simoncostumes/simonawesome/simonawesome.mdl",
        "models/gonzo/simoncostumes/simoncamo/simoncamo.mdl",
        "models/gonzo/simoncostumes/simonhcl/simonhcl.mdl",
        "models/gonzo/simoncostumes/simonhellokitty/simonhellokitty.mdl",
        "models/gonzo/simoncostumes/simonmoddb/simonmoddb.mdl",
        "models/gonzo/simoncostumes/simonsicksimon/simonsicksimon.mdl",
    },
    description = [[У тебя можно найти все, что душе угодно. Только во время торговли не попадись на глаза взрослым - они этого не любят.']],
    weapons = {},
    command = "bariga",
    max = 3,
    salary = GAMEMODE.Config.normalsalary,
    admin = 0,
    vote = false,
    hasLicense = false,
    cook = true,
    category = "Школьники",
    pupil = true,
})

TEAM_FEMINE = DarkRP.createJob("Школьница", {
    color = Color(183, 46, 114, 255),
    model = {
        "models/player/group01/dahlia0o0.mdl",
        "models/player/korka007/maxc.mdl",
    },
    description = [[Самая обычная школьница средней Школы номер 666.]],
    weapons = {},
    command = "femine",
    max = 0,
    salary = GAMEMODE.Config.normalsalary,
    admin = 0,
    vote = false,
    hasLicense = false,
    category = "Школьники",
    pupil = true,
})

TEAM_SEX = DarkRP.createJob("Отличница", {
    color = Color(200, 200, 62, 255),
    model = {
        "models/nikout/carleypm.mdl",
        "models/players/mj_linda.mdl",
    },
    description = [[Отличница посещает все уроки без исключения и безответно помогает школьным красавчикам.]],
    weapons = {},
    command = "otlichnica",
    max = 1,
    salary = GAMEMODE.Config.normalsalary,
    admin = 0,
    vote = false,
    hasLicense = false,
    category = "Школьники",
    pupil = true,
})

local teacherMdls = {
    "models/humans/group02/player/tale_04.mdl",
    "models/humans/group02/player/tale_06.mdl",
    "models/humans/group02/player/tale_07.mdl",
    "models/humans/group02/player/tale_08.mdl",
    "models/humans/group02/player/tale_09.mdl",
    "models/humans/group02/player/temale_02.mdl",
    "models/humans/group02/player/temale_07.mdl",
    "models/humans/groupap/mapert_02.mdl",
    "models/humans/groupap/mapert_04.mdl",
    "models/humans/groupap/mapert_06.mdl",
    "models/humans/groupap/mapert_08.mdl",
    "models/player/breen.mdl",
    "models/player/mossman.mdl",
    "models/player/eli.mdl",
    "models/11thdoctor/thedoctor.mdl",
    "models/bmscientistcits/p_female_01.mdl",
    "models/players/mj_yseb.mdl",
    "models/rottweiler/bale.mdl",
    "models/suka_player.mdl",
    "models/player/aiden_pearce.mdl",
    "models/bmscientistcits/p_female_02.mdl",
    "models/bmscientistcits/p_female_03.mdl",
    "models/bmscientistcits/p_female_04.mdl",
    "models/bmscientistcits/p_female_06.mdl",
    "models/bmscientistcits/p_female_07.mdl",
    "models/bmscientistcits/p_male_01.mdl",
    "models/bmscientistcits/p_male_02.mdl",
    "models/bmscientistcits/p_male_03.mdl",
    "models/bmscientistcits/p_male_04.mdl",
    "models/bmscientistcits/p_male_05.mdl",
    "models/bmscientistcits/p_male_06.mdl",
    "models/bmscientistcits/p_male_07.mdl",
    "models/bmscientistcits/p_male_08.mdl",
    "models/bmscientistcits/p_male_09.mdl",
    "models/bmscientistcits/p_male_10.mdl",
}
local teacher = function(name, desc, cmd, subject, addWeapons)
    local weapons = {"arrest_stick", "unarrest_stick", "stunstick", "door_ram", "weaponchecker", "swep_mark"}
    if addWeapons then
        for i,v in ipairs(addWeapons) do
            table.insert(weapons, v)
        end
    end

    return DarkRP.createJob("Учитель " .. name, {
        color = Color(25, 128, 255),
        model = teacherMdls,
        description = desc,
        weapons = weapons,
        command = cmd,
        max = 1,
        salary = GAMEMODE.Config.normalsalary * 2,
        admin = 0,
        vote = true,
        category = "Взрослые",
        subject = subject,
    })
end

TEAM_TEACHER_MATH = teacher('Математики',
    [[Один из самых нелюбимых учителей в школе. Потому что никто не знает эту гребаную математику...]],
    'teacher_math',
    "Математика"
)

TEAM_TEACHER_BIO = teacher('Биологии',
    [[Расскажи детям, как устроен этот мир изнутри. Опасайся вопросов про половую жизнь.]],
    'teacher_bio',
    "Биология"
)

TEAM_TEACHER_HISTORY = teacher('Истории',
    [[Расскажи, как все было на самом деле. Ну и пусть, что все дети называют тебя динозавром.]],
    'teacher_history',
    "История"
)

TEAM_TEACHER_RUS = teacher('Русского',
    [[Настоящий патриот русского языка, получаешь наслаждение, указывая людям на их ошибки.]],
    'teacher_rus',
    "Русский"
)

TEAM_TEACHER_FOREIGN = teacher('Иностранного',
    [[Лет ми спик фром май харт. Что тут еще можно сказать?]],
    'teacher_foreign',
    "Иностранный"
)

TEAM_TEACHER_GEOGRAPHY = teacher('Географии',
    [[Расскажи детям, как отличить Австралию от Авcтрии. Ну или хотя бы сориентироваться в школе.]],
    'teacher_geography',
    "География"
)

TEAM_TEACHER_PHYS = teacher('Физики',
    [[Покажи детям, что магия - это не магия, а простые трюки. Хотя... Они все равно не поймут.]],
    'teacher_phys',
    "Физика"
)

TEAM_TEACHER_CHEM = teacher('Химии',
    [[Сделай из учеников гуру зельеварения, только не взорви всю школу к чертям. И не дай этого сделать ученикам.]],
    'teacher_chem',
    "Химия"
)

TEAM_TEACHER_ICT = teacher('Информатики',
    [[С твоими знаниями ты бы мог взломать пентагон, но зарплата учителя тебя устраивает.]],
    'teacher_ict',
    "Информатика"
)

TEAM_TEACHER_CULTURE = teacher('Культуры',
    [[Помоги детям поверить, что в этом мире осталось еще хоть что-то прекрасное. Ну или объясни, почему нет.]],
    'teacher_culture',
    "Культура"
)

TEAM_TEACHER_LITERATURE = teacher('Литературы',
    [[Заставляй детей учить стишки, которые они завтра же забудут. Ну или расскажи какую-нибудь классную историю.]],
    'teacher_literature',
    "Литература"
)

TEAM_TEACHER_SPORT = teacher('Физры',
    [[Любимый учитель в школе. Половину уроков вы играете в футбольчик, а другой половины вообще нет и все уходят домой пораньше.]],
    'teacher_sport',
    "Физра",
    { 'swep_team' }
)

TEAM_TEACHER_CRAFT = teacher('Труда',
    [[Ты можешь собрать всё что угодно из палок, говна и бутылки водки. Тебе плевать на технику безопасности, хоть на одном из уроков ты и потерял свою ногу.]],
    'teacher_craft',
    "Труд"
)

TEAM_MEDIC = DarkRP.createJob("Мед. работник", {
    color = Color(70, 40, 100, 255),
    model = {
        "models/vlrpgaming/hospitalfemale01.mdl",
        "models/vlrpgaming/hospitalfemale03.mdl",
        "models/vlrpgaming/hospitalfemale05.mdl",
        "models/vlrpgaming/hospitalmale01.mdl",
        "models/vlrpgaming/hospitalmale03.mdl",
        "models/vlrpgaming/hospitalmale05.mdl",
    },
    description = [[Универсальная инструкция: Если вдруг к тебе придут с открытым переломом или пробитой головой, дай активированный уголь.]],
    weapons = {"med_kit"},
    command = "medic",
    max = 5,
    salary = GAMEMODE.Config.normalsalary,
    admin = 0,
    vote = false,
    hasLicense = false,
    medic = true,
    category = "Взрослые",
})

TEAM_GUARD = DarkRP.createJob("Охранник", {
    color = Color(29, 21, 188, 255),
    model = {
        "models/player/kerry/policeru_01.mdl",
        "models/player/kerry/policeru_02.mdl",
        "models/player/kerry/policeru_03.mdl",
        "models/player/kerry/policeru_05.mdl",
        "models/player/kerry/policeru_06.mdl",
        "models/player/kerry/policeru_07.mdl",
    },
    description = [[Был недавно уволен из пятерочки за приставания к кассиршам. Следи за порядком и арестовывай нарушителей.]],
    weapons = {"arrest_stick", "unarrest_stick", "stunstick", "door_ram", "weaponchecker"},
    command = "guard",
    max = 5,
    salary = GAMEMODE.Config.normalsalary * 2,
    PlayerLoadout = function(ply) ply:SetBodygroup(2, 1) end,
    admin = 0,
    vote = false,
    hasLicense = true,
    chief = true,
    category = "Взрослые",
})

TEAM_PRISONGUARD = DarkRP.createJob("Смотритель тюрьмы", {
    color = Color(128, 64, 255),
    model = {
        "models/player/kerry/policeru_10.mdl",
        "models/player/kerry/policeru_11.mdl",
        "models/player/kerry/policeru_12.mdl",
        "models/player/kerry/policeru_13.mdl",
        "models/player/kerry/policeru_14.mdl",
        "models/player/kerry/policeru_15.mdl",
    },
    description = [[Охраняй выход из тюрьмы и следи, чтобы дети там не шумели.]],
    weapons = {"arrest_stick", "unarrest_stick", "stunstick", "door_ram", "weaponchecker"},
    command = "prisonguard",
    max = 3,
    salary = GAMEMODE.Config.normalsalary * 3,
    admin = 0,
    vote = true,
    hasLicense = true,
    category = "Взрослые",
})

TEAM_CLEANER = DarkRP.createJob("Уборщик", {
    color = Color(120, 80, 33, 255),
    model = {
        "models/humans/group02/player/tale_03.mdl",
        "models/humans/group02/player/tale_05.mdl",
    },
    description = [[Пожалуй, ты больше всех ненавидишь этих маленьких засранцев, раскидывающих бумажки налево и направо.]],
    weapons = {"stunstick"},
    command = "cleaner",
    max = 3,
    salary = GAMEMODE.Config.normalsalary * 2,
    admin = 0,
    vote = false,
    hasLicense = false,
    category = "Взрослые",
})

TEAM_VACHT = DarkRP.createJob("Вахтер", {
    color = Color(120, 80, 33, 255),
    model = {
        "models/humans/group02/player/tale_03.mdl",
        "models/humans/group02/player/tale_05.mdl",
    },
    description = [[Следи за тем, чтобы ученики не убегали из школы. Ах да... Также проверяй сменку.]],
    weapons = {"stunstick"},
    command = "vacht",
    max = 3,
    salary = GAMEMODE.Config.normalsalary * 2,
    admin = 0,
    vote = false,
    hasLicense = false,
    category = "Взрослые",
})

TEAM_LIBRARY = DarkRP.createJob("Библиотекарь", {
    color = Color(237, 124, 38),
    model = {
        "models/player/mossman.mdl",
    },
    description = [[У тебя можно найти самые редкие и интересные истории. Следи за читальным залом и следи за тишиной.]],
    weapons = {"arrest_stick", "unarrest_stick", "stunstick", "weaponchecker"},
    command = "library",
    max = 1,
    salary = GAMEMODE.Config.normalsalary * 2,
    admin = 0,
    vote = false,
    hasLicense = false,
    category = "Взрослые",
})

if not DarkRP.disabledDefaults["modules"]["hungermod"] then
    TEAM_COOK = DarkRP.createJob("Повар", {
        color = Color(238, 99, 99, 255),
        model = {
            "models/fearless/chef1.mdl",
            "models/fearless/chef2.mdl",
            "models/cultist/bbq_m.mdl",
            "models/cultist/bbq_f.mdl",
        },
        description = [[Не важно, что ты приготовишь, дети все равно купят эти дурацкие пиццы, из-за которых все всегда бегут к медику.]],
        weapons = {"weapon_hl2pan"},
        command = "cook",
        max = 2,
        salary = 45,
        admin = 0,
        vote = false,
        hasLicense = false,
        cook = true,
        category = "Взрослые",
    })
end

TEAM_DIRECTOR = DarkRP.createJob("Директор", {
    color = Color(196, 0, 0, 255),
    model = "models/doktor_haus/watson/watson.mdl",
    description = [[Пусть даже все твои обязанности заключаются в составлении устава и расписания, изображай, что ты ведешь бурную деятельность.]],
    weapons = {"arrest_stick", "unarrest_stick", "stunstick", "weaponchecker", "swep_mark"},
    command = "director",
    max = 1,
    salary = GAMEMODE.Config.normalsalary * 5,
    admin = 0,
    vote = true,
    hasLicense = false,
    mayor = true,
    category = "Взрослые",
})

TEAM_ADMIN = DarkRP.createJob("Модератор", {
    color = Color(255, 196, 64, 255),
    model = {
        "models/player/soldier_stripped.mdl",
        "models/player/p2_chell.mdl",
        "models/player/dewobedil/danganronpa/togami/default_p.mdl",
        "models/models/konnie/sherlock/sherlock.mdl",
    },
    description = [[Использую эту профессию, когда разбираешь с жалобами.]],
    weapons = {"weapon_knife", "slappers", "swep_team"},
    command = "admin",
    max = 0,
    salary = 0,
    admin = 0,
    vote = false,
    hasLicense = true,
    candemote = false,
    hobo = false,
    customCheck = function( ply ) return ply:GetUserGroup() ~= 'user' and ply:GetUserGroup() ~= 'vip' end,
    customCheckFailMsg = "Ты должен быть модером что бы стать им!",
    category = "Другое",
})

TEAM_MUSIC = DarkRP.createJob("Музыкант", {
    color = Color(128, 128, 256, 255),
    model = "models/player/alyx.mdl",
    description = [[Всем уже осточертело слушать звук этого звонка. Разнообразь школьную атмосферу.]],
    command = "music",
    max = 3,
    salary = GAMEMODE.Config.normalsalary * 2,
    admin = 0,
    vote = false,
    hasLicense = false,
    candemote = true,
    hobo = false,
    customCheck = function( ply ) return ply:IsVIP() end,
    customCheckFailMsg = "Ты должен быть VIP что бы стать им!",
    category = "VIP профессии",
    pupil = true,
})

TEAM_GRAFFITY = DarkRP.createJob("Вандал", {
    color = Color(0, 255, 168, 255),
    model = "models/half-dead/2spookyguys/player/david leatherhoff.mdl",
    description = [[Главное в жизни - созидание. Но это не про тебя. Ты все время таскаешь за пазухой баллончик с краской и стараешься испортить внешний вид всего, что только видишь.]],
    command = "graffity",
    weapons = {"weapon_spraymhs", 'unarrest_stick'},
    max = 1,
    salary = GAMEMODE.Config.normalsalary,
    admin = 0,
    vote = false,
    hasLicense = false,
    candemote = true,
    hobo = false,
    customCheck = function( ply ) return ply:IsVIP() end,
    customCheckFailMsg = "Ты должен быть VIP что бы стать им!",
    category = "VIP профессии",
    pupil = true,
})

-- TEAM_PHOTOSERVICE = DarkRP.createJob("Фотосервис", {
-- 	color = Color(196, 196, 255),
-- 	model = "models/player/hostage/hostage_01.mdl",
-- 	description = [[Может купить LRP Photoprint и печатать фото/картинки по URL адресу!]],
-- 	weapons = {},
-- 	command = "photoservice",
-- 	max = 1,
-- 	salary = GAMEMODE.Config.normalsalary * 3,
-- 	admin = 0,
-- 	vote = false,
-- 	hasLicense = false,
-- 	candemote = true,
-- 	hobo = false,
-- 	customCheck = function( ply ) return ply:IsVIP() end,
--     customCheckFailMsg = "Ты должен быть VIP что бы стать им!",
-- 	category = "VIP профессии",
-- })

TEAM_BLOGGER = DarkRP.createJob("Лайв-Блоггерша", {
    color = Color(255, 92, 119, 255),
    model = "models/player/spike/vamp.mdl",
    description = [[Всем жутко интересна твоя жизнь. Поэтому у тебя есть портативная камера, транслирующая видео на все телевизоры сервера.]],
    command = "blogger",
    weapons = {"swep_newscamera"},
    max = 1,
    salary = GAMEMODE.Config.normalsalary * 2,
    admin = 0,
    vote = false,
    hasLicense = false,
    candemote = true,
    hobo = false,
    customCheck = function( ply ) return ply:IsVIP() end,
    customCheckFailMsg = "Ты должен быть VIP что бы стать им!",
    category = "VIP профессии",
    pupil = true,
})

TEAM_HULIGANVIP = DarkRP.createJob("Опасный хулиган", {
    color = Color(63, 63, 63, 255),
    model = {
        "models/player/bully/hal/hal.mdl",
        "models/player/bully/johnny/johnny.mdl",
        "models/player/bully/norton/norton.mdl",
        "models/player/bully/peanut/peanut.mdl",
        "models/player/bully/davis/davis.mdl",
        "models/player/bully/tom/tom.mdl",
        "models/player/bully/trent/trent.mdl",
    },
    description = [[С этим парнем точно не стоит слакиваться лицом к лицу в пустом коридоре.]],
    weapons = {'weapon_bat'},
    command = "huliganvip",
    max = 3,
    salary = GAMEMODE.Config.normalsalary,
    admin = 0,
    vote = false,
    customCheck = function( ply ) return ply:IsVIP() end,
    customCheckFailMsg = "Ты должен быть VIP что бы стать им!",
    hasLicense = false,
    category = "VIP профессии",
    pupil = true,
})

TEAM_STERVA = DarkRP.createJob("Стерва", {
    color = Color(63, 63, 63, 255),
    model = {
        "models/mark2580/resident2/moira_prisoner_player.mdl",
    },
    description = [[Любит тусоваться и заводить романы на недельку, а затем расставаться со смачной пощечиной.]],
    weapons = {"slappers", "weapon_kiss"},
    command = "sterva",
    max = 3,
    salary = GAMEMODE.Config.normalsalary,
    admin = 0,
    vote = false,
    customCheck = function( ply ) return ply:IsVIP() end,
    customCheckFailMsg = "Ты должен быть VIP что бы стать ей!",
    hasLicense = false,
    category = "VIP профессии",
    pupil = true,
})

TEAM_BARIGAVIP = DarkRP.createJob("Прошаренный барыга", {
    color = Color(173, 173, 173, 255),
    model = {
        "models/gonzo/simoncostumes/simon/simon.mdl",
        "models/gonzo/simoncostumes/simonaom/simonaom.mdl",
        "models/gonzo/simoncostumes/simonawesome/simonawesome.mdl",
        "models/gonzo/simoncostumes/simoncamo/simoncamo.mdl",
        "models/gonzo/simoncostumes/simonhcl/simonhcl.mdl",
        "models/gonzo/simoncostumes/simonhellokitty/simonhellokitty.mdl",
        "models/gonzo/simoncostumes/simonmoddb/simonmoddb.mdl",
        "models/gonzo/simoncostumes/simonsicksimon/simonsicksimon.mdl",
    },
    description = [[Ну у тебя-то точно можно найти все и даже больше.]],
    weapons = {'weapon_vape'},
    command = "barigavip",
    max = 3,
    salary = GAMEMODE.Config.normalsalary,
    admin = 0,
    vote = false,
    hasLicense = false,
    customCheck = function( ply ) return ply:IsVIP() end,
    customCheckFailMsg = "Ты должен быть VIP что бы стать ей!",
    cook = true,
    category = "VIP профессии",
    pupil = true,
})

TEAM_DOG = DarkRP.createJob("Собака", {
    color = Color(255, 196, 64, 255),
    model = "models/doge_player/doge_player.mdl",
    description = [[Это собака. Какое еще описание ты ожидал увидеть?!]],
    weapons = {},
    command = "dog",
    max = 3,
    salary = 0,
    admin = 0,
    vote = false,
    hasLicense = false,
    candemote = true,
    hobo = false,
    category = "Другое",
    PlayerLoadout = function(ply)
        ply:Give('swep_bark')
        return true
    end
})

TEAM_BANNED = DarkRP.createJob("Изгой", {
    color = Color(0, 0, 0, 255),
    model = {
        "models/player/charple.mdl"
    },
    description = [[Забаненный игрок. Лучше им не становиться.]],
    weapons = {},
    command = "iambanned",
    max = 0,
    salary = 0,
    admin = 0,
    vote = false,
    hasLicense = false,
    candemote = false,
    category = "Другое",

    PlayerLoadout = function( ply )
        return true
    end,
    PlayerSpawn = function(ply)
        local scale = 0.2
        ply:SetModelScale( scale, 0 )
        ply:SetViewOffset( Vector(0, 0, 64) * scale )
        ply:SetViewOffsetDucked( Vector(0, 0, 28) * scale )
        ply:SetWalkSpeed( GAMEMODE.Config.walkspeed * math.pow(scale, 0.5) )
        ply:SetRunSpeed( GAMEMODE.Config.runspeed * math.pow(scale, 0.5) )
        ply.jobScale = true
    end,


    customCheck = function(ply)
        return false
    end,
    customCheckFailMsg = "Зачем тебе это?"
})

-- Compatibility for when default teams are disabled
TEAM_CITIZEN = TEAM_CITIZEN  or -1
TEAM_POLICE  = TEAM_POLICE   or -1
TEAM_GANG    = TEAM_GANG     or -1
TEAM_MOB     = TEAM_MOB      or -1
TEAM_GUN     = TEAM_GUN      or -1
TEAM_MEDIC   = TEAM_MEDIC    or -1
TEAM_CHIEF   = TEAM_CHIEF    or -1
TEAM_MAYOR   = TEAM_MAYOR    or -1
TEAM_HOBO    = TEAM_HOBO     or -1
TEAM_COOK    = TEAM_COOK     or -1

-- Door groups
AddDoorGroup("Для взрослых",
    TEAM_TEACHER_MATH,
    TEAM_TEACHER_LITERATURE,
    TEAM_TEACHER_GEOGRAPHY,
    TEAM_TEACHER_HISTORY,
    TEAM_TEACHER_CULTURE,
    TEAM_MEDIC,
    TEAM_TEACHER_BIO,
    TEAM_TEACHER_SPORT,
    TEAM_TEACHER_PHYS,
    TEAM_TEACHER_FOREIGN,
    TEAM_TEACHER_CHEM,
    TEAM_TEACHER_ICT,
    TEAM_TEACHER_RUS,
    TEAM_TEACHER_CRAFT,
    TEAM_VACHT,
    TEAM_GUARD,
    TEAM_PRISONGUARD,
    TEAM_DIRECTOR,
    TEAM_LIBRARY,
    TEAM_CLEANER
)
AddDoorGroup("Кабинет директора",
    TEAM_GUARD,
    TEAM_PRISONGUARD,
    TEAM_DIRECTOR,
    TEAM_CLEANER,
    TEAM_LIBRARY
)
AddDoorGroup("Закрыто")

-- Agendas
DarkRP.createAgenda("Чат хулиганов", {TEAM_HULIGAN})
DarkRP.createAgenda("Объявления", {TEAM_DIRECTOR}, {TEAM_TEACHER_MATH, TEAM_TEACHER_LITERATURE, TEAM_TEACHER_GEOGRAPHY, TEAM_TEACHER_HISTORY, TEAM_MEDIC, TEAM_TEACHER_CULTURE, TEAM_TEACHER_BIO, TEAM_TEACHER_SPORT, TEAM_TEACHER_PHYS, TEAM_TEACHER_FOREIGN, TEAM_TEACHER_CHEM, TEAM_TEACHER_ICT, TEAM_TEACHER_RUS, TEAM_PRISONGUARD, TEAM_GUARD, TEAM_MEDIC})

-- Group chats
DarkRP.createGroupChat(function(ply) return ply:isCP() end)
DarkRP.createGroupChat(function(ply) return not ply:isCP() end)
DarkRP.createGroupChat(TEAM_HULIGAN)
DarkRP.createGroupChat(function(listener, ply) return not ply or ply:Team() == listener:Team() end)

-- Initial team when first spawning
GAMEMODE.DefaultTeam = TEAM_SHKOLNIK

-- Teams that belong to Civil Protection
GAMEMODE.CivilProtection = {
    [TEAM_TEACHER_MATH] = true,
    [TEAM_TEACHER_SPORT] = true,
    [TEAM_TEACHER_PHYS] = true,
    [TEAM_TEACHER_FOREIGN] = true,
    [TEAM_TEACHER_RUS] = true,
    [TEAM_TEACHER_CHEM] = true,
    [TEAM_TEACHER_ICT] = true,
    [TEAM_TEACHER_CRAFT] = true,
    [TEAM_TEACHER_CULTURE] = true,
    [TEAM_TEACHER_BIO] = true,
    [TEAM_TEACHER_GEOGRAPHY] = true,
    [TEAM_TEACHER_HISTORY] = true,
    [TEAM_TEACHER_LITERATURE] = true,
    [TEAM_GUARD] = true,
	[TEAM_PRISONGUARD] = true,
    [TEAM_DIRECTOR] = true,
    [TEAM_MEDIC] = true,
    [TEAM_COOK] = true,
    [TEAM_CLEANER] = true,
    [TEAM_LIBRARY] = true,
    [TEAM_VACHT] = true,
}

-- Hitman team
//DarkRP.addHitmanTeam(TEAM_MOB)

-- Demote groups
DarkRP.createDemoteGroup("Взрослые", {TEAM_DIRECTOR,
    TEAM_TEACHER_LITERATURE,
    TEAM_TEACHER_BIO,
    TEAM_TEACHER_GEOGRAPHY,
    TEAM_TEACHER_CULTURE,
    TEAM_MEDIC,
    TEAM_TEACHER_HISTORY,
    TEAM_TEACHER_MATH,
    TEAM_TEACHER_SPORT,
    TEAM_TEACHER_PHYS,
    TEAM_TEACHER_FOREIGN,
    TEAM_TEACHER_RUS,
    TEAM_TEACHER_CHEM,
    TEAM_TEACHER_ICT,
    TEAM_TEACHER_CRAFT,
    TEAM_PRISONGUARD,
    TEAM_GUARD,
    TEAM_MEDIC,
    TEAM_LIBRARY,
    TEAM_CLEANER
})
//DarkRP.createDemoteGroup("Gangsters", {TEAM_GANG, TEAM_MOB})

-- Default categories
DarkRP.createCategory{
    name = "Школьники",
    categorises = "jobs",
    startExpanded = true,
    color = Color(0, 107, 0, 255),
    canSee = fp{fn.Id, true},
    sortOrder = 100,
}

DarkRP.createCategory{
    name = "Взрослые",
    categorises = "jobs",
    startExpanded = true,
    color = Color(25, 25, 170, 255),
    canSee = fp{fn.Id, true},
    sortOrder = 101,
}

DarkRP.createCategory{
    name = "VIP профессии",
    categorises = "jobs",
    startExpanded = true,
    color = Color(100, 50, 50, 255),
    canSee = fp{fn.Id, true},
    sortOrder = 104,
}

DarkRP.createCategory{
    name = "Другое",
    categorises = "jobs",
    startExpanded = true,
    color = Color(0, 107, 0, 255),
    canSee = fp{fn.Id, true},
    sortOrder = 255,
}
